version: '1.0'

services:
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./docker-conf/redis_data:/data

  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-conf/mysql_data:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
       - ./docker-conf/rabbitmq_data/data/:/var/lib/rabbitmq/
       - ./docker-conf/rabbitmq_data/log/:/var/log/rabbitmq
